[package]
name = "simple-api-aks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[target.x86_64-unknown-linux-musl]
linker = "rust-lld"

[dependencies]
actix-web = "4.5"
log = "0.4"
pretty_env_logger = "0.5"
